#!/usr/bin/dotnet run
// Generates CLI help documentation for the Shelly CLI by invoking `shelly cli xmldoc`.

#:sdk Microsoft.NET.Sdk
#:property TargetFramework=net10.0
#:property Nullable=enable
#:property ImplicitUsings=enable

using System.Diagnostics;
using System.Text;
using System.Xml.Linq;

const string shellyBin = "shelly";
const string outputFile = "wiki/cli_help.md";

var xml = RunXmlDoc();
var doc = XDocument.Parse(xml);

// Flat list of <Command> elements directly under <Model>
var commands = doc.Root?.Elements("Command").ToList()
               ?? throw new InvalidOperationException("Unexpected xmldoc structure: missing <Model> root.");

Directory.CreateDirectory(Path.GetDirectoryName(outputFile)!);

var sb = new StringBuilder();
sb.AppendLine("# Shelly CLI Documentation");
sb.AppendLine();
sb.AppendLine("> Auto-generated by `help_compiler.cs`. Do not edit manually.");

foreach (var cmd in commands)
{
    var name = cmd.Attribute("Name")?.Value ?? "";
    var isBranch = cmd.Attribute("IsBranch")?.Value == "true";
    var isDefault = cmd.Attribute("IsDefault")?.Value == "true";

    // Use "shelly" as the display name for the default command
    var displayPath = isDefault ? "shelly" : $"shelly {name}";

    var description = cmd.Element("Description")?.Value.Trim() ?? "";

    var arguments = cmd.Element("Parameters")?.Elements("Argument").ToList() ?? [];
    var options = cmd.Element("Parameters")?.Elements("Option").ToList() ?? [];
    var examples = GroupExamples(cmd.Element("Examples")?.Elements("Example").ToList() ?? [], name);

    sb.AppendLine();
    sb.AppendLine($"## `{displayPath}`");
    sb.AppendLine();

    if (!string.IsNullOrWhiteSpace(description))
    {
        sb.AppendLine(description);
        sb.AppendLine();
    }

    if (isBranch)
    {
        sb.AppendLine("*Branch command — use one of the subcommands.*");
        sb.AppendLine();
    }

    if (arguments.Count > 0)
    {
        sb.AppendLine("**Arguments:**");
        sb.AppendLine();
        foreach (var arg in arguments)
        {
            var argName = arg.Attribute("Name")?.Value ?? "ARG";
            var required = arg.Attribute("Required")?.Value == "true";
            var argDesc = arg.Element("Description")?.Value.Trim() ?? "";
            var reqMarker = required ? " *(required)*" : "";
            sb.AppendLine($"- `<{argName}>`{reqMarker} — {argDesc}");
        }

        sb.AppendLine();
    }

    if (options.Count > 0)
    {
        sb.AppendLine("**Options:**");
        sb.AppendLine();
        foreach (var opt in options)
        {
            var shortOpt = opt.Attribute("Short")?.Value ?? "";
            var longOpt = opt.Attribute("Long")?.Value ?? "";
            var required = opt.Attribute("Required")?.Value == "true";
            var optDesc = opt.Element("Description")?.Value.Trim() ?? "";
            var reqMarker = required ? " *(required)*" : "";

            var flags = new[]
            {
                string.IsNullOrEmpty(shortOpt) ? null : $"-{shortOpt}",
                string.IsNullOrEmpty(longOpt) ? null : $"--{longOpt}"
            }.Where(f => f != null);

            sb.AppendLine($"- `{string.Join(", ", flags)}`{reqMarker} — {optDesc}");
        }

        sb.AppendLine();
    }

    if (examples.Count > 0)
    {
        sb.AppendLine("**Examples:**");
        sb.AppendLine();
        sb.AppendLine("```sh");
        foreach (var ex in examples)
            sb.AppendLine($"shelly {ex}");
        sb.AppendLine("```");
    }
}

File.WriteAllText(outputFile, sb.ToString());
Console.WriteLine($"Documented {commands.Count} commands.");
Console.WriteLine($"Documentation written to {outputFile}");
return;

#region Helpers

static string RunXmlDoc()
{
    try
    {
        var psi = new ProcessStartInfo(shellyBin, ["cli", "xmldoc"])
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false
        };

        using var proc = Process.Start(psi)!;
        var stdout = proc.StandardOutput.ReadToEnd();
        proc.WaitForExit();

        return string.IsNullOrWhiteSpace(stdout)
            ? throw new InvalidOperationException("No output from 'shelly cli xmldoc'.")
            : stdout;
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine($"ERROR: Could not run '{shellyBin} cli xmldoc': {ex.Message}");
        Console.Error.WriteLine("Build and install the project first (dotnet publish Shelly-CLI).");
        Environment.Exit(1);
        return "";
    }
}

// Each argument in WithExample("a", "b", "c") becomes a separate <Example commandLine="..." />.
// We regroup them into full example lines by splitting on occurrences of the command name token.
static List<string> GroupExamples(List<XElement> elements, string commandName)
{
    var tokens = elements.Select(e => e.Attribute("commandLine")?.Value ?? "").ToList();
    if (tokens.Count == 0) return [];

    var result = new List<string>();
    var current = new List<string>();

    foreach (var token in tokens)
    {
        // A new example starts when we see the command name again (and we already have tokens)
        if (token == commandName && current.Count > 0)
        {
            result.Add(string.Join(" ", current));
            current.Clear();
        }

        current.Add(token);
    }

    if (current.Count > 0)
        result.Add(string.Join(" ", current));

    return result;
}

#endregion